
# name: Build test

# on:
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
    # - uses: actions/checkout@v2
    # - uses: DoozyX/clang-format-lint-action@v0.12
    #   with:
    #     clangFormatVersion: 12
    #     extensions: 'java'